name: Other Branches Workflow

on:
  push:
    branches-ignore: [master]  # Trigger on push events to any branch except main
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: npm test
      - name: Build project
        run: npm run build
